### PR TITLE
Twelve of Code removed <!DOCTYPE html> and <body> elements from challenges

### PR DESCRIPTION
**Pull request by Mesure73L**
Issue #38

### CODE REVIEW

**Comment by Mesure73L** [comment]
Completed and tested, merge when ready

**Comment by BeepBot99** [comment]
I'll test it on my own. I'll merge it when it's ready.

**Comment by Mesure73L** [comment]
@BeepBot99 merge when you finished looking at this

**Comment by Mesure73L** [comment]
Please merge as soon as possible but **do not delete the branch**, I will still be working in it.

**Comment by BeepBot99** [comment]
Okay, it is now merged.

**Pull request merged**
